version: "3.7"

networks:
  default:
    external:
      name: carwow

services:
  app:
    container_name: rubydoc
    image: 127.0.0.1:5000/rubydoc-app
    labels:
      - carwow
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - "7890:8080"
        # depends_on:
        #  - docparse

        # docparse:
        #   image: 127.0.0.1:5000/rubydoc-docparse
        #   container_name: rubydoc-docparse
        #   build:
        #     context: ./docker/docparse
        #   entrypoint: sh -c "echo Docparse image is built. It is okay for this service to exit."
